version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/data/db
    networks:
      - sistca_net
    ports:
      - "27017:27017"
    logging:
      driver: none
      
  nodeapp:
    build: .
    container_name: nodeapp
    restart: always
    depends_on: 
      - mongodb
    networks:
      - sistca_net
    ports:
      - "8081:3000"

volumes:
  data:
    driver: local
  
networks:
  sistca_net:
    ipam:
      driver: default
      config:
        - subnet: 172.200.1.0/24
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: sistca_isep